spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod

---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_HOST}:3306/gaseng
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 50

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 2592000
  refresh-token-validity: 2592000

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

logging:
  level:
    com:
      amazonaws:
        util.EC2MetadataUtils: error
        internal.InstanceMetadataServiceResourceFetcher: error

#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace

coolsms:
  api:
    key: ${COOL_KEY}
    secret: ${COOL_SECRET}
    phone: ${COOL_PHONE}

metamask:
  WALLET_ADDRESS: ${WALLET_ADDRESS}
  CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
  PRIVATE_KEY: ${WALLET_PRIVATE_KEY}

infura:
  API_URL: ${INFURA_API_URL}